### ISSUE TITLE
Possible error in the name of the GOST R 34.10 2012 algorithm.

### ISSUE THREAD

**Issue by rv-borisov** [kmvi/bc-signedxml#6]
Hello! Thanks for the functionality you provide.
I found a discrepancy between the names of the algorithms GOST R 34.10 2012 in you and in CryptoPro.

This makes it impossible to sign documents using bc-xml-security with subsequent verification through CryptoPro, and vice versa. I believe that this problem will also be observed when interacting with various organizations that require the signing of documents/requests.

These are the algorithms:

**GOST R 34.10 2012 256**

bc-xml-security in `SignedXml.XmlDsigGost3410_2012_256_Url`:
`urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012256`

CryptoPro:
`urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012-256`

**GOST R 34.10 2012 512**

bc-xml-security in `SignedXml.XmlDsigGost3410_2012_256_Url`:
`urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012512`

CryptoPro:
`urn:ietf:params:xml:ns:cpxmlsec:algorithms:gostr34102012-gostr34112012-512`

Hope you fix this. Thanks a lot again!

**Comment by kmvi** [comment]
Thanks for the report!
