### ISSUE TITLE
Possibility to add custom transforms

### ISSUE THREAD

**Issue by Hiller** [kmvi/bc-signedxml#7]
I have custom transforms for XML, but those custom transforms are not in CryptoHelpers

I guess there are should be a method like 
`CryptoHelpers.Add<T,TImplementation>(string urn)`
so we'll be able to register and use custom transforms like

`CryptoHelpers.Add<Transform,MyCustomTransform>(urn)`

**Comment by kmvi** [comment]
You can use `CryptoHelpers.SetKnownName<CustomTransform>("urn:custom-transform")`.
